production:
  auto_deploy_on: refs/heads/master
  environment: production
  production_environment: true
  required_contexts: ["build", "deliverybot/promoted"]

staging:
  auto_deploy_on: refs/heads/master
  environment: staging
  production_environment: false
  required_contexts: ["build"]

review:
  environment: pr${{ pr }}
  transient_environment: true
  production_environment: false
